default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  database: <%= ENV["DB_NAME"] %>
  pool: <%= ENV["RAILS_MAX_THREADS"] { 5 } %>
  port: 5432

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV["DB_NAME"] %>_test

production:
  <<: *default
